SNSTopicCloudWatchAlarm:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "cloudwatch-alarm-topic"
      KmsMasterKeyId: !Sub 'alias/${ClusterName}_sns-alias'
      Subscription:
        - Endpoint: "anvesh.muppeda@gmail.com"
          Protocol: "email"
      TopicName: "cloudwatch-alarm-topic"

  CloudWatchAlaramWorkers:
    DependsOn: SNSTopicCloudWatchAlarm
    Type: AWS::CloudWatch::Alarm
    Properties:
        AlarmName: !Sub '${Environment}-${ClusterName}_worker-failures'
        AlarmDescription: |-
            In the EKS DCTM-Cluster Cluster, one or more worker nodes are having issues.
        ActionsEnabled: true
        OKActions: []
        AlarmActions:
            - !FindInMap [Environment, !Ref Environment , CWSNSArn]
        InsufficientDataActions: []
        MetricName: cluster_failed_node_count
        Namespace: ContainerInsights
        Statistic: Average
        Dimensions:
            - Name: ClusterName
              Value: !Ref ClusterName
        Period: 60
        EvaluationPeriods: 5
        DatapointsToAlarm: 3
        Threshold: 90
        ComparisonOperator: GreaterThanThreshold
        TreatMissingData: missing
